---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_action
  retries: 100
  until: apt_action is success
  tags:
  - apt_update

- name: Install binaries
  apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{  binaries }}"
  notify: "{{ handler_list }}"
  tags:
  - apt_install
